version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=vaultbox
      - DB_PASSWORD=supersecret
      - DB_NAME=vaultbox
      - MASTER_PASSWORD=changeme
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: vaultbox
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: vaultbox
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 