version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: vaultbox
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: vaultbox
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=vaultbox
      - DB_PASSWORD=supersecret
      - DB_NAME=vaultbox
      - MASTER_PASSWORD=changeme
    depends_on:
      - postgres
    networks:
      - vaultbox-network

networks:
  vaultbox-network:
    driver: bridge

volumes:
  pgdata:
